package fis.test;
// Generated by ComTest BEGIN
import java.util.Date;
import static org.junit.Assert.*;
import org.junit.*;
import static fis.Parse.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.04 22:36:21 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class ParseTest {



  // Generated by ComTest BEGIN
  /** testParseDouble20 */
  @Test
  public void testParseDouble20() {    // Parse: 20
    assertEquals("From: Parse line: 21", -1, parseDouble(null), 0.000001); 
    assertEquals("From: Parse line: 22", -1, parseDouble(""), 0.000001); 
    assertEquals("From: Parse line: 23", -1, parseDouble("j238"), 0.000001); 
    assertEquals("From: Parse line: 24", 0.0, parseDouble("0.0"), 0.000001); 
    assertEquals("From: Parse line: 25", 56.67, parseDouble("56.67"), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParseInt45 */
  @Test
  public void testParseInt45() {    // Parse: 45
    assertEquals("From: Parse line: 46", -1, parseInt(null)); 
    assertEquals("From: Parse line: 47", -1, parseInt("")); 
    assertEquals("From: Parse line: 48", -1, parseInt("mi6")); 
    assertEquals("From: Parse line: 49", 0, parseInt("0")); 
    assertEquals("From: Parse line: 50", -747, parseInt("-747")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testParseDate71 
   * @throws fis.SailoException when error
   */
  @Test
  public void testParseDate71() throws fis.SailoException {    // Parse: 71
    Date date = parseDate("2001-01-16", "yyyy-MM-dd"); 
    Date date2 = new Date(101, 0, 16); 
    assertEquals("From: Parse line: 76", true, date.equals(date2)); 
    try {
    parseDate("2001-01-16", "yyyy.MM.dd"); 
    fail("Parse: 77 Did not throw fis.SailoException");
    } catch(fis.SailoException _e_){ _e_.getMessage(); }
    Date date3 = parseDate("51-01-16", "yyyy-MM-dd"); 
    Date date4 = new Date(-1849, 0, 16); 
    assertEquals("From: Parse line: 80", true, date3.equals(date4)); 
  } // Generated by ComTest END
}