package fis.test;
// Generated by ComTest BEGIN
import java.io.IOException;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import fis.Tulos;
import static org.junit.Assert.*;
import org.junit.*;
import fis.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.05 11:25:09 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class SeurantaTest {



  // Generated by ComTest BEGIN
  /** testLisaa30 */
  @Test
  public void testLisaa30() {    // Seuranta: 30
    Seuranta seuranta = new Seuranta(); 
    assertEquals("From: Seuranta line: 32", 0, seuranta.getList().size()); 
    int y = 5; 
    for (int i=0; i<y; i++) {
    seuranta.lisaa(new Integer(0)); 
    }
    assertEquals("From: Seuranta line: 37", y, seuranta.getList().size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista51 */
  @Test
  public void testPoista51() {    // Seuranta: 51
    Seuranta seuranta = new Seuranta(); 
    assertEquals("From: Seuranta line: 53", 0, seuranta.getList().size()); 
    int y = 5; 
    for (int i=0; i<y; i++) {
    seuranta.lisaa(new Integer(0)); 
    }
    assertEquals("From: Seuranta line: 58", y, seuranta.getList().size()); 
    seuranta.poista(new Integer(1)); 
    assertEquals("From: Seuranta line: 60", y, seuranta.getList().size()); 
    seuranta.poista(new Integer(0)); 
    assertEquals("From: Seuranta line: 62", 0, seuranta.getList().size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetList80 */
  @Test
  public void testGetList80() {    // Seuranta: 80
    Seuranta seuranta = new Seuranta(); 
    assertEquals("From: Seuranta line: 82", 0, seuranta.getList().size()); 
    int y = 5; 
    for (int i=0; i<y; i++) {
    seuranta.lisaa(new Integer(0)); 
    }
    assertEquals("From: Seuranta line: 87", y, seuranta.getList().size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testParse100 
   * @throws SailoException when error
   */
  @Test
  public void testParse100() throws SailoException {    // Seuranta: 100
    Seuranta seuranta = new Seuranta(); 
    assertEquals("From: Seuranta line: 103", 0, seuranta.getList().size()); 
    seuranta.parse("1"); 
    seuranta.parse("3"); 
    assertEquals("From: Seuranta line: 106", 2, seuranta.getList().size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testSeurannassa125 
   * @throws SailoException when error
   */
  @Test
  public void testSeurannassa125() throws SailoException {    // Seuranta: 125
    Seuranta seuranta = new Seuranta(); 
    assertEquals("From: Seuranta line: 128", true, seuranta.seurannassa(1234) == false); 
    seuranta.parse("1234"); 
    assertEquals("From: Seuranta line: 130", false, seuranta.seurannassa(1234) == false); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta145 
   * @throws IOException when error
   */
  @Test
  public void testLueTiedostosta145() throws IOException {    // Seuranta: 145
    String tiedosto = "testiSeuranta.csv"; 
    String otsake = "comma,separated,value"; 
    Seuranta seuranta = new Seuranta(); 
    assertEquals("From: Seuranta line: 153", 0, seuranta.getList().size()); 
    VertaaTiedosto.kirjoitaTiedosto(tiedosto,
    otsake + "\n" +
    "1\n" +
    "2\n" +
    "3"); 
    seuranta.lueTiedostosta(seuranta, tiedosto, otsake); 
    assertEquals("From: Seuranta line: 160", 3, seuranta.getList().size()); 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTallennaTiedostoon173 
   * @throws IOException when error
   * @throws SailoException when error
   */
  @Test
  public void testTallennaTiedostoon173() throws IOException, SailoException {    // Seuranta: 173
    String tiedosto = "testiSeuranta.csv"; 
    String otsake = "comma,separated,value"; 
    Seuranta seuranta = new Seuranta(); 
    assertEquals("From: Seuranta line: 181", 0, seuranta.getList().size()); 
    VertaaTiedosto.kirjoitaTiedosto(tiedosto,
    otsake + "\n" +
    "1\n" +
    "2\n" +
    "3"); 
    seuranta.lueTiedostosta(seuranta, tiedosto, otsake); 
    assertEquals("From: Seuranta line: 188", 3, seuranta.getList().size()); 
    seuranta.poista(new Integer(2)); 
    seuranta.tallennaTiedostoon(seuranta, tiedosto, "tmpTestiSeuranta.csv", otsake); 
    String tulos =
    otsake + "\n" +
    "1\n" +
    "3\n"; 
    assertEquals("From: Seuranta line: 195", null, VertaaTiedosto.vertaaFileString(tiedosto, tulos)); 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
  } // Generated by ComTest END
}