package fis.test;
// Generated by ComTest BEGIN
import java.util.List;
import java.io.IOException;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import fis.Urheilija;
import static org.junit.Assert.*;
import org.junit.*;
import fis.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.05 00:57:55 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class UrheilijatTest {



  // Generated by ComTest BEGIN
  /** testLisaa51 */
  @Test
  public void testLisaa51() {    // Urheilijat: 51
    Urheilijat urheilijat = new Urheilijat(); 
    assertEquals("From: Urheilijat line: 53", 0, urheilijat.getList().size()); 
    int y = 5; 
    for (int i=0; i<y; i++) {
    urheilijat.lisaa(new Urheilija()); 
    }
    assertEquals("From: Urheilijat line: 58", y, urheilijat.getList().size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGet83 
   * @throws SailoException when error
   */
  @Test
  public void testGet83() throws SailoException {    // Urheilijat: 83
    Urheilijat urheilijat = new Urheilijat(); 
    Urheilija urheilija = new Urheilija(); 
    String rivi = "278,13th FIS points list 2018/2019,1,AL,O,219656,502468,AABERG,Filip,SWE,M,2001-10-19,Nolby Alpina,SWE,AABERG Filip,2001,191.08,1587,+,66.57,1817,,77.99,2430,,131.07,2036,*,,,"; 
    urheilija.parse(rivi); 
    urheilijat.lisaa(urheilija); 
    int y = 5; 
    for (int i=0; i<y; i++) {
    urheilijat.lisaa(new Urheilija()); 
    }
    urheilijat.get(502468).equals(urheilija); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetList110 
   * @throws SailoException when error
   */
  @Test
  public void testGetList110() throws SailoException {    // Urheilijat: 110
    Urheilijat urheilijat = new Urheilijat(); 
    assertEquals("From: Urheilijat line: 114", 0, urheilijat.getList().size()); 
    urheilijat.lueTiedostosta(); 
    List<Urheilija> listUrheilijat = urheilijat.getList(); 
    assertEquals("From: Urheilijat line: 117", true, listUrheilijat.size() > 0); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetLkm130 
   * @throws SailoException when error
   */
  @Test
  public void testGetLkm130() throws SailoException {    // Urheilijat: 130
    Urheilijat urheilijat = new Urheilijat(); 
    assertEquals("From: Urheilijat line: 133", 0, urheilijat.getLkm()); 
    urheilijat.lueTiedostosta(); 
    int lkm = urheilijat.getLkm(); 
    assertEquals("From: Urheilijat line: 136", true, lkm > 10); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta329 
   * @throws IOException when error
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta329() throws IOException, SailoException {    // Urheilijat: 329
    String tiedosto = "testiUrheilijat.csv"; 
    String otsake = "Listid,Listname,Published,Sectorcode,Status,Competitorid,Fiscode,Lastname,Firstname,Nationcode,Gender,Birthdate,Skiclub,Nationalcode,Competitorname,Birthyear,DHpoints,DHpos,DHSta,SLpoints,SLpos,SLSta,GSpoints,GSpos,GSSta,SGpoints,SGpos,SGSta,ACpoints,ACpos,ACSta"; 
    String u1 = "278,\"13th FIS points list 2018/2019\",1,AL,O,219656,502468,AABERG,Filip,SWE,M,2001-10-19,\"Nolby Alpina\",SWE,\"AABERG Filip\",2001,191.08,1587,+,66.57,1817,,77.99,2430,,131.07,2036,*,,,"; 
    String u2 = "278,\"13th FIS points list 2018/2019\",1,AL,O,219656,1234,AABERG,Filip,SWE,M,2001-10-19,\"Nolby Alpina\",SWE,\"AABERG Filip\",2001,191.08,1587,+,66.57,1817,,77.99,2430,,131.07,2036,*,,,"; 
    String u3 = "278,\"13th FIS points list 2018/2019\",1,AL,O,219656,5678,AABERG,Filip,SWE,M,2001-10-19,\"Nolby Alpina\",SWE,\"AABERG Filip\",2001,191.08,1587,+,66.57,1817,,77.99,2430,,131.07,2036,*,,,"; 
    Urheilijat urheilijat = new Urheilijat(); 
    VertaaTiedosto.kirjoitaTiedosto(tiedosto,
    otsake + "\n" +
    u1 + "\n" +
    u2 + "\n" +
    u3 + "\n"); 
    assertEquals("From: Urheilijat line: 346", 0, urheilijat.getLkm()); 
    urheilijat.lueTiedostosta(urheilijat, Urheilija.class, tiedosto, otsake); 
    assertEquals("From: Urheilijat line: 348", 3, urheilijat.getLkm()); 
    assertEquals("From: Urheilijat line: 349", false, urheilijat.get(5678) == null); 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
  } // Generated by ComTest END
}